// Auto-generated from gmail-addon/citation-map.json.
// Maps base filename (no extension) → Drive file ID for the preferred
// version of each policy (PDF preferred over DOCX over MD). Used by
// Code.gs's citationToDriveUrl_() to render Vertex AI citations as
// clickable Drive links.
//
// Stored as a .gs file rather than a Script Property because the map
// exceeds the 9 KB per-property limit. To regenerate after policy doc
// changes, see scripts/build-citation-map.py in the repo.

const CITATION_MAP_DATA = {
  "Appendix Form A - Employee Acknowledgement Form": "1KrQUnh1rsMld18KKGvAwakcc2OT3krSp",
  "Appendix Form B - Conflict of Interest Disclosure Statement Form": "1LXQIIbxxyA4M2nkcrAzJsc_6R8XJIfpu",
  "Appendix Form C - Emergency Information Form": "17qwOwv8kznug2VM2WSaDPemzo7sZDr8I",
  "BENA-1 Workers Compensation Insurance Guidelines": "1Pb-T8Vp2SmVf8dyv8AD8jiusEMKKEz4L",
  "BENA-1 Workers Compensation Insurance Policy": "1Z85K7csyBBDouLMKADGkCpk6OBOg_gfG",
  "BENA-2 Deferred Compensation Policy": "1fY39kLMt362LZaq9b9vYSaJJ4svIFBJD",
  "BENA-3 Flexible Spending Accounts Policy": "1oI8YarAm0gagUTwA4c50HlEIRew70vDb",
  "BENA-4 Sick Leave Policy": "1mLoOtNml8zGj0oHV5foqFovHMKhChhe2",
  "BENR-1 Health Insurance Policy": "1SJOZfyO9ZfkIzaDhCyfuo75ME7egAldI",
  "BENR-10 Military Leave Policy": "1q2OMdCeaKd1E1en849_ytyZj9LCz9TLa",
  "BENR-2 Pension Policy": "1fFM4Y38PAiawfXgPJwgYdNwevxOvl0jT",
  "BENR-3 Legal Insurance Policy": "1Tr_uKvTwbyHg_1-cOMdZFkhkLV3xOWZI",
  "BENR-4 Vacation Leave Policy": "1nlz7_AdWL0G4TpIsXdwBxaVx8cQjqx2O",
  "BENR-5 Sick Leave Policy": "1j2EkWcbC_jHr6ZN_oT8SrZtXjr7Z5xFg",
  "BENR-5a Emergency Paid Sick Leave Policy": "1Xzp_-Qetem21H4EuiPU8g8JZhQpV3V7m",
  "BENR-6 Bereavement Leave Policy": "1xzt75p3jZbgrh8NRozhvkwrbBoMp1PEw",
  "BENR-7 Jury Duty and Civil Appearance Leave Policy": "1kbknDz9t7MdwX0qOZc1ubJpofS0BHYd7",
  "BENR-8 Leaves of Absence FMLA Policy": "1LY3pIUA2ZKZQcQdaUgFn4LcWG6e3Hek-",
  "BENR-8a Leaves of Absence - Expanded FMLA Policy": "15jfQnZGDvCLlg8bQCIxgVzBgIdQpU1ym",
  "BENR-9 Disability Insurance Policy": "1rUNF56Ky6YgzOdYMMc1KsQ7aG26ApVGy",
  "CIRC-1 Library Card Guidelines": "1aQUGJbHoFt5qwXApHLl2QI00PE5L3EVs",
  "CIRC-1 Library Card Policy": "1hvaqfwC4Gl9YAX00b0yNqPivzwB254DB",
  "CIRC-2 Loan and Renewal Guidelines": "1hUr_mUjnwjQi3_JWdXI7JuaQWYRXPC8i",
  "CIRC-2 Loan and Renewal Policy": "1VGjAv8oPrbLkqTrp9UC7f8RcIo8NFRbG",
  "CIRC-3 Holds Guidelines": "1BMOoIBn8kfppRfzvYkNA9kVgLyieLFB_",
  "CIRC-3 Holds Policy": "12E3rd4NMdNbGuzx0liroPuqWQ1S533GI",
  "CIRC-4 Fines and Fees Guidelines": "1bk5sgWJyN-71JXIVWueNv7tus26nCY60",
  "CIRC-4 Fines and Fees Policy": "1i4HRJP4WLMjrZYPeQ_NGjPK8_9bA8MNq",
  "CIRC-4 Misplaced Items Form": "1TVCyxiOwl4Rm2ULXSV5B1uivmn-XUyDl",
  "CIRC-5 Lost or Damaged Missing Pieces Guidelines": "1nIdX_-wSpUGCAv1-K2hZ5K2pnbYBwKEK",
  "CIRC-5 Lost or Damaged Missing Pieces Policy": "1qRaCz7mhhdtdhdWPFKdMFI8i93y0roft",
  "CUS-1 Customer Service Guidelines": "1sU27MIjp4W9BSS3GSJ_1vYQ3MTiu9kkP",
  "CUS-1 Customer Service Policy": "1M_SAMVwDLUNAY_pGQtic-Weq35m1V65k",
  "CUS-2 Code of Conduct Guidelines": "1OEaK8qRz4tjcIaGB7Hh_pB_a5wcCwWw_",
  "CUS-2 Code of Conduct Policy": "1e9iJ77MTKPVUWNlmzsKU-dc4JYXw9RJW",
  "CUS-2a Code of Conduct Policy during COVID-19 Pandemic Policy": "1D7ZrewaDRclfXGmOwGg8nNYT9M3zAphn",
  "CUS-2a Code of Conduct Policy during COVID-19 Pandemic Policy(1)": "1J_nDrnzJZz2SzECI04KkFQbBzPmzg56s",
  "CUS-3 Appeals Process for Disciplinary Action Policy": "1boq2zLYTo7xZmlUBtwmJz-fcurEjSKBR",
  "CUS-4 Unattended Children Guidelines": "1cDeOg5-qXujxMjouO2UMCguY48zR61aB",
  "CUS-4 Unattended Children Policy": "1AsMq77h0wyjeG5YGY1UfsYMzWKlpsOOQ",
  "Code of Ethics of the American Library Association": "1HDzGmSn__eFVehxKtCT81-PPEbUUScU5",
  "FOIA Procedures": "1h_kpvtlL36LVhx8nz9x47vQNrP5Vor2U",
  "GEN-1 Introduction": "1TS0C-ygIRRSTsGrOXigrZGexfudMV9CA",
  "GEN-2 Definitions": "1cS2uTedf3YV2WtqlacOw6LQ5s5ZrA4jM",
  "GEN-3 Equal Opportunity Employer Policy": "1U4QRx7kMi23OmY5VkBL1W8Ug1GLPMJFZ",
  "GEN-4 Hiring Guidelines": "1tP3wXaP-Zog48JlCvIL-KoA_ONboxMw6",
  "GEN-4 Hiring Policy": "1obtE8ovfi0ClK-lP0h7qRnHVGIga7f2D",
  "GEN-5 At-Will Employment Policy": "11E3s9AlvBRQMOKI1ThGB645AQvPhFzOF",
  "GOV-1 Library Establishment Policy": "1TyBE4DT2RmviVVbwgqi518LVC5xOBe0m",
  "GOV-2 Philosophical Principles Policy": "1sfLsW63Gj5SWegkvqlPMF_1qESW7LjJ9",
  "GOV-3 Hours of Service Guidelines": "1ObJEVZZc_YMY2uRFSQnlzXns92-65uMm",
  "GOV-3 Hours of Service Policy": "11V-wGh2CYNmJtlaR3X99sHKAZ2OuscKg",
  "GOV-5 Library Board Committees Policy": "1WTPIQBm_G2f_b-jjRblUf5bXTf8A0UW2",
  "GOV-6  Library Board Ethics and Conflict of Interest Policy": "1ypHHDg2Ua-IWdJCJ-V-ZEso8LYPiXdql",
  "GOV-7  Whistleblower Policy": "1mDd9IgF5SaUWUs6GABVbLQAE_aAonoXP",
  "GOV-8 Environmental Impact Policy": "15jng7nr7ha1KcjlZxdiltNlVxXIveyyc",
  "GSV-1 Programs in the Library Guidelines": "1l0zpaC-Jy0t_9DzXB1u-yFOtRxzA2UJB",
  "GSV-1 Programs in the Library Policy": "1BUNCs0rSrGsfURUKRPcWNVoWogqRYlw6",
  "GSV-2 Community Presentations Guidelines": "1nhzc5FmGwPeuFwnvCE88CjYw8Faj2pgZ",
  "GSV-2 Community Presentations Policy": "1xb4J9LTbuSCoLkbFTQjnsf_Ptq3Uqddm",
  "GSV-3 Proctoring Examinations Policy": "1F0vuVJ1Rp473AkKt6gCiSXt5IwVbfLMx",
  "GSV-4 Makerspace Policy": "14BviqxqFy9rk9NmB1GnevTqjNo5pSg_j",
  "GSV-4 Makerspace Release Form": "1GVBL-tqcZ1vNp5E4l-3dCLbtDQ4xAV_A",
  "INF-1 Materials Selection Collection Development Guidelines": "1FWckdo2mnwuIZClm_Vb4Sb99zS_ZR1fq",
  "INF-1 Materials Selection Collection Development Policy": "1E3kdu4bS2tXiBSiA522lFJlYestd-370",
  "INF-2 Information Services Guidelines": "1LwIWJYTR4BlMC8XMyDaPVWoZnWW9OTtt",
  "INF-2 Information Services Policy": "1N6OTSndz37nEgrWfb1bMRBwruy7_lHxi",
  "INF-3 Web Site Guidelines": "1kvlkg5azk1hBgEogPaLlJDQP9gOWstVO",
  "INF-3 Web Site Policy": "1khmkjXSK-d2XJlscNjXj7vUMPAPLGp42",
  "INF-4 Internet Access and Use Guidelines": "1i2r3SMJ03f1FVSU6tiLAUhqXna82NDrN",
  "INF-4 Internet Access and Use Policy": "1qFqbk12GIDBKcn2_Wy0KkPo6ZjwDBusm",
  "INF-5 Internet Access for Customer Provided Equipment Guidelines": "1ODqGDlMnzF377Y8VQrwB6UlRlSkAqNgb",
  "INF-5 Internet Access for Customer Provided Equipment Policy": "1LsHWFtRnbIY7tVYMGb-DgIMC20XFwzqV",
  "INF-6 Interlibrary Loan Guidelines": "1yqglSY5xLyqusiilVYBg2X0l9jIANzm0",
  "INF-6 Interlibrary Loan Policy": "1jXcCfO-KacNpue8sLCOoycHS2H6m975h",
  "INF-7 Artificial Intelligence (AI) Policy": "1wZ-TXzWpo_ZFRO_gOM9WP85gZXgLsCvN",
  "Library Bill of Rights": "1tHZWBrpCK1g6sPh8KU5_40ORvbspXTJC",
  "MGT-1 Confidentiality of Library Records Guidelines": "1pBA3ptDfO0pkgw4qXPuCFVJw9suucq_v",
  "MGT-1 Confidentiality of Library Records Policy": "1uTY3nWNgwXxYZGT6u95DwJmOB9_Hh7rq",
  "MGT-10 Meeting Room Policy": "1ORtWHYQKAwj1RCMLYSiW7cB0IQMHyvum",
  "MGT-10 Meeting Room Use Guidelines": "1DuIZ4AWYtdtq9wdemMR_9GF_G1qvvPBZ",
  "MGT-11 Displays and Distribution of Non-library Materials Guidelines": "1q2TdHG6Y8JjgHk6iWTYdgmnbF84SuRPu",
  "MGT-11 Displays and Distribution of Non-library Materials Policy": "13vIeRRPYQec8iSOh5GX3wFp_q9cm7dwx",
  "MGT-12 Media Relations Guidelines": "19uKsxOnSV6mDs7cmUS7koExA-ToMxwL9",
  "MGT-12 Media Relations Policy": "1XgKKyb7yICm2MmX9mLwdxbiQ3Wyb4EOz",
  "MGT-13 Building Maintenance Guidelines": "1rdrlIMlKydqIoZmaP8Yrh8awI0f0qASm",
  "MGT-14 Volunteer Policy": "17yFrtJrY7jrtX_4J5uWWURHRnnoJuxeT",
  "MGT-14 Volunteers Guidelines": "1GCWgv6LCCeES1uvDcI0T7jlK_ISZnJjN",
  "MGT-15 FOIA Guidelines (Writen Summary of Procedures and Guidelines)": "14hJXgUX9uE6kEFP3NDch7RZIOudQyDBe",
  "MGT-15 FOIA Policy": "1oDlQubXWZZ0H5raeQblX2dKhNAIppbdb",
  "MGT-15-Freedom of Information - Detailed Itemization Costs": "1-qSDU9CoC_PSxpHi-1IFevXJkMm-aYPP",
  "MGT-16 Social Media Policy": "1N5EYfmVCA8Bj5J4RnqntOxd7S6BDc-v8",
  "MGT-17 Capital Asset Policy": "1TlRqx37-XaGTavhISA7WhEEqXhW6GCXu",
  "MGT-17 Capital Asset Policy.docx": "1svNcw7q-rrqbrKPN_JBn3vd8725xy2Ql",
  "MGT-18 Fund Balance Policy": "1mRHElFWXhG4kD0SCYxeHy3zgY0XEmHDe",
  "MGT-2 Records Retention Guidelines": "1CAeG9tG-KMZFOlcgp-dDOsU8gGelza5O",
  "MGT-2 Records Retention Policy": "1rA10D0uGOwPIa_DHzHQ_omMWw_spnC8e",
  "MGT-3 Financial Guidelines": "1rfgjB3wSGYApvf2cPWXs4Beq_uxdatH5",
  "MGT-3 Financial Policy": "14J8GDLBYl-T4FqyyoSyQ2r3w7vj6Bp5e",
  "MGT-4 Investment Guidelines": "1uArQLYZmPix8ZL3g1CJTW4AQaCRP_ABc",
  "MGT-4 Investment Policy": "1weXwaaxpGOhXA_E_6NrlRBzMBKb9dwL8",
  "MGT-5 Gifts and Donations Guidelines": "1Qjd1J-dBtKd4BHTebqW_bSFeXGVNSaGk",
  "MGT-5 Gifts and Donations Policy": "1jSyYDJTqfLrHypTCBfHLukR9dr5FJkV0",
  "MGT-6 Endowment Fund Guidelines": "10BQbssMYnJU6B-GUJSXmhb4HUV6pNrGM",
  "MGT-6 Endowment Fund Policy": "1Uu5t9bCVMubF75EG_ChCgExU4A6abPA2",
  "MGT-7 Reconsideration of Library Materials Form (aka Statement of Concern form)": "1qhF33Q5_rrm1yN75x4q2s5DDyzsUTiyb",
  "MGT-7 Reconsideration of Library Materials Guidelines": "1ZNgalictpIbCqCl6AJGH_aZfDPC8_a20",
  "MGT-7 Reconsideration of Library Materials Policy": "19OHb-u3chNt_ks5UJzeO8sDDYAjEvqY3",
  "MGT-8 Temporary Closures Guidelines": "1OxJipy7JkEtsp2yvLev2c1Cb6SBfThKf",
  "MGT-8 Temporary Closures Policy": "1EF3hjxMA-08Iz0Nw3ODIBmHYlEJqx_mf",
  "MGT-9 Library Group Study Tables and Room Guidelines": "1ojf_sSWhV3hGzXOgtvtKcFBl9_4A-CEf",
  "MGT-9 Library Group Study Tables and Room Policy": "14wnuQJv4GsOciSgDHFL9s3uPFWb1THLJ",
  "MISC-1 Authorization and Release Form": "1LgJFsIYtKnUGkVX2-iIb6nNoqwYdQxgU",
  "MISC-1 Personnel Records Policy": "1hmtvCr1r_3UEmo9iZNFTud-4OgrkDO6z",
  "MISC-2 Social Security Number Privacy Policy": "1QOA_FFFFfvZuOoRIIUCC2UmW5S1gTmKj",
  "MISC-3 Credit Card Policy": "12WbFUYJZ4upJVBmlpOansFy3kxXQ4RKM",
  "PAY-1 Wage and Salary Administration Guidelines": "1tRxuuX5MKxv3WY3Jyo12sywFy1VE0UkZ",
  "PAY-1 Wage and Salary Administration Policy": "1BwHvFXCfGNyJjZXCiH5Fx0V_FL61nSAX",
  "PAY-2 Schedules Guidelines": "1HKvzabc-YvxxfxGivZj096gap-U0uTQ8",
  "PAY-2 Schedules Policy": "17gZmB9qc3UI5JwAR0nngcxg_qqL4JYi7",
  "PAY-3 Compensatory Time Policy": "1Hl4vkmw0jZ5HRkKg9gjNXRDD6Qgh4hVL",
  "PAY-4 Holiday Pay Policy": "1jb_UAulJOckAStClKBgozVrMDMNykwRG",
  "PAY-5 Emergency Closing Policy": "1otHLjxZVif1TIKJD2e2EwuEwNOF-69i2",
  "PAY-6 Furlough Day Policy": "1UcHxmRkUEjjurxErpmLOe4owXtd0Ex_p",
  "PERF-1 Positions and Standards Guidelines": "1PxqIwRklikqw0JOTW0TEhzZEYs1ndGI-",
  "PERF-1 Positions and Standards Policy": "1XX3A_Fgj2JsMQjAjCtBQ-CjWVQGFR39o",
  "PERF-2 Professional Development Guidelines": "1AA0FExYcO899Cn6ksd_N0YnfaNRk5Gd7",
  "PERF-2 Professional Development Policy": "1nX4Oj_gKzIfgVWEVivMb1hsIOLwSd3Yb",
  "PERF-3 Performance Evaluations Guidelines": "1Ghq9q2styW4_RfgJxx6DhGKK4aq8UhEa",
  "PERF-3 Performance Evaluations Policy": "1l7OCZZtXDltB09h2lJ5jFu3JgBzSxL1j",
  "PERF-3 Performance Evaluations for Library Director Guidelines": "15OktjkTBSderyhPrB7UAcJ0ezisZou3j",
  "PERF-4 Placement Reassignment and Promotion Policy": "1fPbh4pqW9hr-ITRz3TNwtibtVr3mwEDK",
  "PERF-5 Separation from Service Policy": "1kHwHPFO0dMj55or_gV-5Uc9Sqs2kMzPC",
  "Patron Card Types - TLN vs MILibrary Preference": "1ejrIl8ta7IGzhmCKg2KLNk4HcuO5AtWA",
  "Photo Release for Adults Form": "14W9IKrMyT-Ktd8iuGFlYC4xkerHJBkKM",
  "Photo Release for Minors Form": "11gtlTj5gyqFAjrkyYcjrLYq53qJQoCO_",
  "RHPL Staff Phone Directory": "1Ev2uAzr_3ZhjfrLx5Qce_76agLEkPJGw",
  "Reconsideration of Library Materials Form": "1hSiSgyUVX-mv1Mo2hZilaKEwOor1ddX4",
  "Table of Contents": "1EL9gJOrB9Ols1KtKPk8x14u6_hSrYIrq",
  "The Freedom to Read Statement": "16204se9JS_3CGe5r4--B5d4v8n7VA4Ud",
  "WORK-1 Employee Conduct Policy": "1LJlWx8XDz8svp41Bgu4EtF4ToyYOE7aK",
  "WORK-10 Telework Guidelines": "1G7_R6VeOTFO98piJGcRGhXUGVGZfk5YP",
  "WORK-10 Telework Policy": "1Utyyc3YC8dJWaW7kdjSCffpO2f9IowFB",
  "WORK-11 Employee Use of Social Media Guidelines": "1k7LHig6SFu-eXebxkeK3uhZK2QVRuthq",
  "WORK-11 Employee Use of Social Media Policy": "1tiEthZ9BGjPDkSaj04GiaADTIy1CE_-g",
  "WORK-12 Drug Free Workplace Policy": "1pmvaCVN16nF2EubnFWXaZ-BWoKTlA_XF",
  "WORK-13 Employee Use of Artificial Intelligence (AI)": "1wv89Uoh7-kcSStLujpr9m2SLCu70mdMV",
  "WORK-13 Employee Use of Artificial Intelligence (AI) _": "1-NOZMvcDO4FKNW66ulOAGT1ngb-6B4Is",
  "WORK-2 Anti Harassment Guidelines": "17gPE5TPjEoO6tMzl6LR8XVSbLxF-sKVN",
  "WORK-2 Anti Harassment Policy": "15KazBqTVhuNogZXDFRzwUvz6mOldTRz_",
  "WORK-3 Accommodation of Disabilities Policy": "169S7i0Q0yylFpC09-1ZurNicp_1gDcJ7",
  "WORK-4 Complaint Procedure Policy": "1wAYVnWQKph0_3P5E-29r5NMOBb7kz0HQ",
  "WORK-5 Conflict of Interest Policy": "1L6Ld8CkMbwMHr8e6iY6xnpLnQr8JJwP5",
  "WORK-6 Safety and Emergency Preparedness Policy": "1V4gTE19T0ZA5K1qeHBJLrbShvN1fB4i2",
  "WORK-7 Use of Technology Policy": "13tvsJOk8CG7NGeHCXv68xGyY92jEMlJ1",
  "WORK-8 Use of Personal Vehicles Policy": "12_ZOwoLsIs13Gup0nRQNvOZpCTYbI_Br",
  "WORK-9 Dress Code Guidelines": "1dVcUhLtNgo2bs_4MPmP8niTBnGKQ7-gR",
  "WORK-9 Dress Code Policy": "1Yma2eChDe3dZxVq1dN921qJkOlq_nhnR",
  "_HR guidelines on approved leave at RHPL": "1VOxzXUHM5z-lo_F1TbqOQMs1q1QhpoHB"
};
